import mongoose, { Document, Schema } from "mongoose";

/**
 * NotificationAudit — Immutable audit trail for notification delivery.
 *
 * Records every notification generated by the Notification Orchestrator,
 * including source event, actor, target user, channels attempted, and
 * delivery status per channel.
 *
 * - Immutable: no updates or deletes after creation
 * - TTL-based expiration: auto-deletes after 90 days
 * - Queryable by userId, eventType, createdAt
 */

export interface IChannelStatus {
  channel: string;
  status: string;
  sentAt?: Date;
  error?: string;
}

export interface IActor {
  type: string;
  id?: string;
}

export interface INotificationAudit extends Document {
  notificationId: mongoose.Types.ObjectId;
  eventId: string;
  eventType: string;
  userId: mongoose.Types.ObjectId;
  actor: IActor;
  source: string;
  channels: IChannelStatus[];
  priority: string;
  category: string;
  createdAt: Date;
}

const ChannelStatusSchema = new Schema<IChannelStatus>(
  {
    channel: { type: String, required: true },
    status: { type: String, required: true },
    sentAt: { type: Date },
    error: { type: String },
  },
  { _id: false }
);

const NotificationAuditSchema = new Schema<INotificationAudit>(
  {
    notificationId: {
      type: Schema.Types.ObjectId,
      required: true,
    },
    eventId: {
      type: String,
      required: true,
      trim: true,
    },
    eventType: {
      type: String,
      required: true,
      trim: true,
    },
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    actor: {
      type: {
        type: String,
        required: true,
      },
      id: { type: String },
    },
    source: {
      type: String,
      required: true,
      trim: true,
    },
    channels: {
      type: [ChannelStatusSchema],
      default: [],
    },
    priority: {
      type: String,
      required: true,
      trim: true,
    },
    category: {
      type: String,
      required: true,
      trim: true,
    },
    createdAt: {
      type: Date,
      required: true,
      default: Date.now,
    },
  },
  {
    timestamps: false,
    versionKey: false,
  }
);

// TTL index: auto-expire audit records after 90 days
NotificationAuditSchema.index(
  { createdAt: 1 },
  { expireAfterSeconds: 90 * 24 * 60 * 60 }
);

// Query indexes for efficient lookups
NotificationAuditSchema.index({ userId: 1 });
NotificationAuditSchema.index({ eventType: 1 });
NotificationAuditSchema.index({ userId: 1, createdAt: -1 });

const NotificationAudit = mongoose.model<INotificationAudit>(
  "NotificationAudit",
  NotificationAuditSchema
);

export default NotificationAudit;
