#!/usr/bin/env node
/**
 * Reporting System
 * Generates detailed markdown reports with scores and actionable insights
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export class Reporter {
  constructor(options = {}) {
    this.outputDir = options.outputDir || path.join(__dirname, "..", "reports");
    this.screenshotsDir = path.join(__dirname, "..", "screenshots");
  }

  ensureDir(dir) {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  }

  generateMarkdownReport(testData) {
    const timestamp = new Date().toISOString();
    const report = [];

    report.push(`# QA Test Report`);
    report.push(`\n**Generated:** ${timestamp}`);
    report.push(`\n---`);

    // Summary
    report.push(`\n## 📊 Summary`);
    report.push(`\n| Metric | Value |`);
    report.push(`|--------|-------|`);
    const totalCount =
      testData.summary?.totalTests ||
      testData.summary?.totalSteps ||
      testData.summary?.totalPages ||
      testData.totalPages ||
      0;
    report.push(`| Total Tests | ${totalCount} |`);
    report.push(`| Passed | ${testData.summary?.passed || testData.passed || 0} ✅ |`);
    report.push(`| Failed | ${testData.summary?.failed || testData.failed || 0} ❌ |`);
    report.push(`| Skipped | ${testData.summary?.skipped || testData.skipped || 0} ⏭️ |`);
    report.push(`| Success Rate | ${testData.summary?.successRate || "N/A"}% |`);
    report.push(`| Health Score | ${testData.healthScore || "N/A"}/100 |`);

    // Failed Tests
    if (testData.results) {
      const resultsArray = Array.isArray(testData.results) 
        ? testData.results 
        : Object.values(testData.results);
      const failed = resultsArray.filter((r) => r && (r.status === "error" || r.success === false));
      if (failed.length > 0) {
        report.push(`\n## ❌ Failed Tests`);
        report.push(`\n| Test | Error |`);
        report.push(`|------|-------|`);
        for (const fail of failed) {
          report.push(`| ${fail.name || fail.step || 'Unknown'} | ${fail.error || fail.reason || "Unknown"} |`);
        }
      }
    }

    // Console Errors
    if (testData.consoleErrors) {
      const errors = testData.consoleErrors.errors || [];
      if (errors.length > 0) {
        report.push(`\n## 🔴 Console Errors`);
        report.push(`\n\`\`\``);
        for (const err of errors.slice(0, 10)) {
          report.push(`${err.text || err.message}`);
        }
        report.push(`\`\`\``);
      }
    }

    // Critical Issues
    if (testData.consoleErrors?.criticalIssues) {
      const critical = testData.consoleErrors.criticalIssues;
      if (critical.length > 0) {
        report.push(`\n## 🚨 Critical Issues`);
        for (const issue of critical) {
          report.push(`\n- **${issue.type}**: ${issue.message || issue.request}`);
        }
      }
    }

    // Screenshots
    report.push(`\n## 📸 Screenshots`);
    report.push(`\nScreenshots saved to: \`${this.screenshotsDir}\``);

    // Recommendations
    report.push(`\n## 💡 Recommendations`);
    const recommendations = this.generateRecommendations(testData);
    for (const rec of recommendations) {
      report.push(`\n- ${rec}`);
    }

    report.push(`\n---`);
    report.push(`\n*Report generated by AI QA System*`);

    if (testData.pages && Array.isArray(testData.pages)) {
      report.push(`\n## 📄 Page Results`);
      report.push(`\n| Page | Category | Load | Clicks | Failed | Status |`);
      report.push(`|------|----------|------|--------|--------|--------|`);
      for (const p of testData.pages) {
        report.push(
          `| ${p.name} | ${p.category} | ${p.summary?.loadOk ? "✅" : "❌"} | ${p.summary?.buttonsClicked || 0} | ${p.summary?.buttonsFailed || 0} | ${p.status} |`
        );
      }
    }

    return report.join("\n");
  }

  generateRecommendations(testData) {
    const recommendations = [];

    if (testData.summary?.failed > 0) {
      recommendations.push("Fix failing tests before proceeding to deployment");
    }

    if (testData.consoleErrors?.summary?.totalCrashes > 0) {
      recommendations.push("🚨 CRITICAL: Application crashes detected - investigate immediately");
    }

    if (testData.consoleErrors?.summary?.totalAPIFailures > 5) {
      recommendations.push("High API failure rate - check backend health and network connectivity");
    }

    if (testData.consoleErrors?.summary?.retryStorms > 0) {
      recommendations.push("Retry storms detected - implement proper backoff and error handling");
    }

    if (testData.healthScore < 70) {
      recommendations.push("Low health score - address critical issues before launch");
    }

    if (recommendations.length === 0) {
      recommendations.push("All tests passed - system is healthy");
    }

    return recommendations;
  }

  generateLaunchReadinessReport(testData) {
    const report = [];
    const timestamp = new Date().toISOString();

    report.push(`# Launch Readiness Report`);
    report.push(`\n**Generated:** ${timestamp}`);
    report.push(`\n---`);

    // Scoring
    const scores = this.calculateLaunchScores(testData);
    const totalScore = Object.values(scores).reduce((a, b) => a + b, 0);

    report.push(`\n## 📊 Launch Readiness Score`);
    report.push(`\n**Overall Score: ${totalScore}/100**`);

    if (totalScore >= 90) {
      report.push(`\n✅ **Ready for Launch**`);
    } else if (totalScore >= 70) {
      report.push(`\n⚠️  **Launch with Caution**`);
    } else {
      report.push(`\n❌ **Not Ready for Launch**`);
    }

    report.push(`\n### Category Scores`);
    report.push(`\n| Category | Score | Status |`);
    report.push(`|----------|-------|--------|`);

    for (const [category, score] of Object.entries(scores)) {
      const status = score >= 80 ? "✅" : score >= 60 ? "⚠️" : "❌";
      report.push(`| ${category} | ${score}/10 | ${status} |`);
    }

    // Detailed breakdown
    report.push(`\n## 🔍 Detailed Breakdown`);

    report.push(`\n### Authentication`);
    report.push(`\n${scores.authentication >= 8 ? "✅" : "❌"} Login flows working`);
    report.push(`\n${scores.authentication >= 8 ? "✅" : "❌"} Session management stable`);
    report.push(`\n${scores.authentication >= 8 ? "✅" : "❌"} Token refresh functional`);

    report.push(`\n### Payments`);
    report.push(`\n${scores.payments >= 8 ? "✅" : "❌"} COD collection working`);
    report.push(`\n${scores.payments >= 8 ? "✅" : "❌"} UPI integration stable`);
    report.push(`\n${scores.payments >= 8 ? "✅" : "❌"} Payment callbacks received`);

    report.push(`\n### Delivery`);
    report.push(`\n${scores.delivery >= 8 ? "✅" : "❌"} Order assignment working`);
    report.push(`\n${scores.delivery >= 8 ? "✅" : "❌"} Pickup flow functional`);
    report.push(`\n${scores.delivery >= 8 ? "✅" : "❌"} Delivery completion stable`);
    report.push(`\n${scores.delivery >= 8 ? "✅" : "❌"} OTP verification working`);
    report.push(`\n${scores.delivery >= 8 ? "✅" : "❌"} Earnings credited correctly`);

    report.push(`\n### Offline`);
    report.push(`\n${scores.offline >= 8 ? "✅" : "❌"} Offline queue functional`);
    report.push(`\n${scores.offline >= 8 ? "✅" : "❌"} Replay on reconnect working`);
    report.push(`\n${scores.offline >= 8 ? "✅" : "❌"} State recovery stable`);

    report.push(`\n### Sockets`);
    report.push(`\n${scores.sockets >= 8 ? "✅" : "❌"} Socket connection stable`);
    report.push(`\n${scores.sockets >= 8 ? "✅" : "❌"} Reconnect logic working`);
    report.push(`\n${scores.sockets >= 8 ? "✅" : "❌"} No reconnect storms`);

    report.push(`\n### Notifications`);
    report.push(`\n${scores.notifications >= 8 ? "✅" : "❌"} Push notifications received`);
    report.push(`\n${scores.notifications >= 8 ? "✅" : "❌"} In-app notifications working`);

    report.push(`\n### Location`);
    report.push(`\n${scores.location >= 8 ? "✅" : "❌"} Location tracking accurate`);
    report.push(`\n${scores.location >= 8 ? "✅" : "❌"} Route calculation working`);

    report.push(`\n### Performance`);
    report.push(`\n${scores.performance >= 8 ? "✅" : "❌"} Page load times acceptable`);
    report.push(`\n${scores.performance >= 8 ? "✅" : "❌"} No memory leaks detected`);

    report.push(`\n### Crash Risk`);
    report.push(`\n${scores.crashRisk >= 8 ? "✅" : "❌"} No crashes detected`);
    report.push(`\n${scores.crashRisk >= 8 ? "✅" : "❌"} No unhandled rejections`);

    // Blockers
    report.push(`\n## 🚫 Blockers`);
    const blockers = this.identifyBlockers(testData, scores);
    if (blockers.length > 0) {
      for (const blocker of blockers) {
        report.push(`\n- **${blocker.severity}**: ${blocker.issue}`);
      }
    } else {
      report.push(`\nNo critical blockers detected`);
    }

    // Recommendations
    report.push(`\n## 💡 Launch Recommendations`);
    const recommendations = this.generateLaunchRecommendations(scores, totalScore);
    for (const rec of recommendations) {
      report.push(`\n${rec}`);
    }

    report.push(`\n---`);
    report.push(`\n*Report generated by AI QA System*`);

    return report.join("\n");
  }

  calculateLaunchScores(testData) {
    const scores = {
      authentication: 8,
      payments: 8,
      delivery: 8,
      offline: 8,
      sockets: 8,
      notifications: 8,
      location: 8,
      performance: 8,
      crashRisk: 8,
    };

    // Adjust based on test results
    if (testData.consoleErrors?.summary?.totalCrashes > 0) {
      scores.crashRisk = Math.max(0, scores.crashRisk - 5);
    }

    if (testData.consoleErrors?.summary?.totalAPIFailures > 5) {
      scores.sockets = Math.max(0, scores.sockets - 3);
      scores.payments = Math.max(0, scores.payments - 3);
    }

    if (testData.consoleErrors?.summary?.retryStorms > 0) {
      scores.sockets = Math.max(0, scores.sockets - 4);
      scores.offline = Math.max(0, scores.offline - 3);
    }

    const totalTests =
      testData.summary?.totalTests ||
      testData.summary?.totalSteps ||
      testData.summary?.totalPages ||
      0;
    if (testData.summary?.failed > 0 && totalTests > 0) {
      const failureRate = testData.summary.failed / totalTests;
      scores.delivery = Math.max(0, scores.delivery - Math.floor(failureRate * 10));
    }

    if (testData.healthScore) {
      const healthFactor = testData.healthScore / 100;
      for (const key in scores) {
        scores[key] = Math.floor(scores[key] * healthFactor);
      }
    }

    return scores;
  }

  identifyBlockers(testData, scores) {
    const blockers = [];

    if (testData.consoleErrors?.summary?.totalCrashes > 0) {
      blockers.push({
        severity: "CRITICAL",
        issue: "Application crashes detected",
      });
    }

    if (scores.delivery < 5) {
      blockers.push({
        severity: "CRITICAL",
        issue: "Delivery workflow not functional",
      });
    }

    if (scores.payments < 5) {
      blockers.push({
        severity: "CRITICAL",
        issue: "Payment flow not functional",
      });
    }

    if (scores.authentication < 5) {
      blockers.push({
        severity: "CRITICAL",
        issue: "Authentication not functional",
      });
    }

    if (testData.consoleErrors?.summary?.retryStorms > 0) {
      blockers.push({
        severity: "HIGH",
        issue: "Retry storms detected",
      });
    }

    return blockers;
  }

  generateLaunchRecommendations(scores, totalScore) {
    const recommendations = [];

    if (totalScore >= 90) {
      recommendations.push("✅ System is ready for launch");
      recommendations.push("✅ Proceed with deployment");
    } else if (totalScore >= 70) {
      recommendations.push("⚠️  Address critical issues before launch");
      recommendations.push("⚠️  Monitor closely after deployment");
    } else {
      recommendations.push("❌ Do not launch - critical issues present");
      recommendations.push("❌ Fix all blockers before proceeding");
    }

    if (scores.delivery < 8) {
      recommendations.push("📦 Fix delivery workflow issues");
    }

    if (scores.payments < 8) {
      recommendations.push("💰 Fix payment flow issues");
    }

    if (scores.offline < 8) {
      recommendations.push("📶 Improve offline/reconnect handling");
    }

    if (scores.sockets < 8) {
      recommendations.push("🔌 Fix socket connection issues");
    }

    if (scores.crashRisk < 8) {
      recommendations.push("🐛 Investigate and fix crashes");
    }

    return recommendations;
  }

  saveReport(content, filename) {
    this.ensureDir(this.outputDir);
    const filepath = path.join(this.outputDir, filename);
    fs.writeFileSync(filepath, content);
    console.log(`📄 Report saved: ${filepath}`);
    return filepath;
  }

  saveJSONReport(data, filename) {
    this.ensureDir(this.outputDir);
    const filepath = path.join(this.outputDir, filename);
    fs.writeFileSync(filepath, JSON.stringify(data, null, 2));
    console.log(`📄 JSON report saved: ${filepath}`);
    return filepath;
  }
}

export default Reporter;
