import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = "en" | "te" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Translation keys
const translations = {
  en: {
    // Account page
    "account.title": "Account",
    "account.welcome": "Manage your account settings",
    "account.welcome.authenticated": "Welcome back, {{name}}!",
    "account.profile": "Profile",
    "account.profile.description": "Manage your personal information",
    "account.orders": "Orders",
    "account.orders.description": "View your order history",
    "account.settings": "Settings",
    "account.settings.description": "App preferences and configuration",
    "account.notifications": "Notifications",
    "account.notifications.description": "Manage your notification preferences",
    "account.privacy": "Privacy",
    "account.privacy.description": "Control your privacy settings",
    "account.help": "Help & Support",
    "account.help.description": "Get help and contact support",
    "account.logout": "Logout",
    "account.logout.description": "Sign out of your account",
    "account.language": "Language",
    "account.language.description": "Choose your preferred language",
    "account.language.english": "English",
    "account.language.telugu": "తెలుగు",
    "account.language.hindi": "हिन्दी",

    // Profile form
    "profile.edit": "Edit Profile",
    "profile.name": "Name",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.address": "Address",
    "profile.save": "Save Changes",
    "profile.cancel": "Cancel",

    // Common
    "common.shop_now": "Shop Now",
    "common.add_to_cart": "Add to Cart",
    "common.search": "Search",
    "common.cart": "Cart",
    "common.home": "Home",
    "common.categories": "Categories",
    "common.account": "Account",

    // Home page
    "home.for_you": "For You",
    "home.categories": "Categories",
    "home.end_of_products": "End of Products",
    "home.search_placeholder": "Search for products…",

    // Categories page
    "categories.title": "Categories",
    "categories.subtitle": "Browse products by category",
    "categories.chocolates": "Chocolates",
    "categories.ladoos": "Laddus",
    "categories.biscuits": "Biscuits",
    "categories.cakes": "Cakes",
    "categories.hot_snacks": "Hot Snacks",
    "categories.beverages": "Beverages",
    "categories.chocolates_desc": "Sweet chocolate treats",
    "categories.ladoos_desc": "Traditional Indian sweets",
    "categories.biscuits_desc": "Crispy and delicious biscuits",
    "categories.cakes_desc": "Delicious and fresh cakes",
    "categories.hot_snacks_desc": "Spicy and crispy snacks",
    "categories.beverages_desc": "Refreshing drinks and beverages",

    // Bottom navigation
    "nav.home": "Home",
    "nav.categories": "Categories",
    "nav.account": "Account",
    "nav.cart": "Cart",

    // Sorting
    "sort.title": "Sort by",
    "sort.price_low_high": "Price: Low to High",
    "sort.price_high_low": "Price: High to Low",
    "sort.popularity": "Popularity",
    "sort.newest": "Newest Arrivals",
    "sort.best_selling": "Best Selling",

    // Home page extended
    "home.topSelling": "🔥 Top Selling",
    "home.topSellingSubtitle": "Most popular products this week",
    "home.downloadApp": "For better experience, download the Vyapara Setu now",
    "home.downloadAppSub": "Get the best shopping experience with our mobile app",
    "home.downloadBtn": "Download App",
    "home.learnMore": "Learn More",
    "home.deliverTo": "Deliver to",
    "home.searchPlaceholder": "Search for Products, Brands and More",

    // Product
    "product.addToCart": "Add to Cart",
    "product.outOfStock": "Out of Stock",
    "product.inStock": "In Stock",
    "product.topBadge": "Top",
    "product.viewDetails": "View Details",
    "product.mrp": "MRP",
    "product.off": "off",
    "product.weight": "Weight",

    // Cart page
    "cart.title": "My Cart",
    "cart.empty": "Your cart is empty",
    "cart.emptySubtitle": "Add items to get started",
    "cart.subtotal": "Subtotal",
    "cart.deliveryFee": "Delivery Fee",
    "cart.total": "Total",
    "cart.checkout": "Proceed to Checkout",
    "cart.free": "Free",
    "cart.remove": "Remove",
    "cart.continueShopping": "Continue Shopping",
    "cart.items": "items",

    // Checkout page
    "checkout.title": "Checkout",
    "checkout.secureCheckout": "Secure checkout",
    "checkout.deliveryAddress": "Delivery Address",
    "checkout.changeAddress": "Change Address",
    "checkout.paymentMethod": "Payment Method",
    "checkout.editPayment": "Edit Payment Method",
    "checkout.upi": "UPI (Recommended)",
    "checkout.upiDesc": "Pay using Google Pay, PhonePe, Paytm",
    "checkout.upiId": "UPI ID",
    "checkout.upiHint": "Enter your UPI ID. A payment request will be sent to your phone.",
    "checkout.card": "Credit / Debit Card",
    "checkout.cardDesc": "Visa, Mastercard, RuPay",
    "checkout.netbanking": "Net Banking",
    "checkout.netbankingDesc": "Pay directly from your bank",
    "checkout.cod": "Cash on Delivery",
    "checkout.codDesc": "Pay when the order arrives",
    "checkout.reviewItems": "Review items and shipping",
    "checkout.delivery": "Delivery",
    "checkout.orderTotal": "Order Total",
    "checkout.securePayment": "Secure payment by Razorpay",
    "checkout.processing": "Processing…",
    "checkout.pay": "Pay",
    "checkout.addAddressForDelivery": "Add delivery address to calculate delivery fee",
    "checkout.orderSummary": "Order Summary",
    "checkout.placeOrder": "Place Order",
    "checkout.online": "Online Payment",
    "checkout.addAddress": "Add New Address",
    "checkout.selectAddress": "Select Address",
    "checkout.noAddress": "No address selected",

    // Orders page
    "orders.title": "My Orders",
    "orders.empty": "No orders yet",
    "orders.emptySubtitle": "Start shopping to see your orders here",
    "orders.pending": "Pending",
    "orders.confirmed": "Confirmed",
    "orders.processing": "Processing",
    "orders.shipped": "Shipped",
    "orders.delivered": "Delivered",
    "orders.cancelled": "Cancelled",
    "orders.trackOrder": "Track Order",
    "orders.reorder": "Reorder",
    "orders.viewDetails": "View Details",
    "orders.placedOn": "Placed on",
    "orders.total": "Total",

    // Product Detail page
    "productDetail.description": "Description",
    "productDetail.reviews": "Reviews",
    "productDetail.relatedProducts": "Related Products",
    "productDetail.quantity": "Quantity",
    "productDetail.buyNow": "Buy Now",
    "productDetail.specifications": "Specifications",
    "productDetail.brand": "Brand",
    "productDetail.category": "Category",

    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.orContinueWith": "Or continue with",
    "auth.googleLogin": "Continue with Google",
    "auth.name": "Full Name",
    "auth.phone": "Phone Number",
    "auth.createAccount": "Create Account",
    "auth.loginTitle": "Login to your account",
    "auth.signupTitle": "Create your account",
    "auth.rememberMe": "Remember me",

    // Settings page
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account preferences",
    "settings.notifications": "Notification Preferences",
    "settings.orderUpdates": "Order Updates",
    "settings.orderUpdatesDesc": "Get notified about your order status",
    "settings.promotions": "Promotions",
    "settings.promotionsDesc": "Special offers & deals",
    "settings.newsletter": "Newsletter",
    "settings.newsletterDesc": "Weekly updates",
    "settings.sms": "SMS Notifications",
    "settings.smsDesc": "Delivery updates via SMS",
    "settings.appearance": "Appearance",
    "settings.language": "Language",
    "settings.languageDesc": "Select your preferred language",
    "settings.currency": "Currency",
    "settings.currencyDesc": "Display prices in your currency",
    "settings.privacy": "Privacy & Security",
    "settings.changePassword": "Change Password",
    "settings.logout": "Logout",
    "settings.deleteAccount": "Delete Account",
    "settings.deleteWarning": "This action cannot be undone",
    "settings.downloadData": "Download My Data",
    "settings.dangerZone": "Danger Zone",

    // Common extended
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.retry": "Try Again",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.next": "Next",
    "common.done": "Done",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.apply": "Apply",
    "common.clear": "Clear",
    "common.noResults": "No results found",
    "common.seeAll": "See All",
    "common.rupee": "₹",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Info",
    "common.required": "Required",
  },
  te: {
    // Account page
    "account.title": "ఖాతా",
    "account.welcome": "మీ ఖాతా సెట్టింగ్‌లను నిర్వహించండి",
    "account.welcome.authenticated": "స్వాగతం, {{name}}!",
    "account.profile": "ప్రొఫైల్",
    "account.profile.description": "మీ వ్యక్తిగత సమాచారాన్ని నిర్వహించండి",
    "account.orders": "ఆర్డర్‌లు",
    "account.orders.description": "మీ ఆర్డర్ చరిత్రను చూడండి",
    "account.settings": "సెట్టింగ్‌లు",
    "account.settings.description": "అనువర్తన ప్రాధాన్యతలు మరియు కాన్ఫిగరేషన్",
    "account.notifications": "నోటిఫికేషన్‌లు",
    "account.notifications.description":
      "మీ నోటిఫికేషన్ ప్రాధాన్యతలను నిర్వహించండి",
    "account.privacy": "గోప్యత",
    "account.privacy.description": "మీ గోప్యత సెట్టింగ్‌లను నియంత్రించండి",
    "account.help": "సహాయం మరియు మద్దతు",
    "account.help.description": "సహాయం పొందండి మరియు మద్దతును సంప్రదించండి",
    "account.logout": "లాగ్ అవుట్",
    "account.logout.description": "మీ ఖాతా నుండి సైన్ అవుట్ చేయండి",
    "account.language": "భాష",
    "account.language.description": "మీ ఇష్టమైన భాషను ఎంచుకోండి",
    "account.language.english": "English",
    "account.language.telugu": "తెలుగు",
    "account.language.hindi": "हिन्दी",

    // Profile form
    "profile.edit": "ప్రొఫైల్‌ను సవరించండి",
    "profile.name": "పేరు",
    "profile.email": "ఇమెయిల్",
    "profile.phone": "ఫోన్",
    "profile.address": "చిరునామా",
    "profile.save": "మార్పులను సేవ్ చేయండి",
    "profile.cancel": "రద్దు చేయండి",

    // Common
    "common.shop_now": "ఇప్పుడు కొనండి",
    "common.add_to_cart": "కార్ట్‌కు జోడించండి",
    "common.search": "వెతకండి",
    "common.cart": "కార్ట్",
    "common.home": "హోమ్",
    "common.categories": "వర్గాలు",
    "common.account": "ఖాతా",

    // Home page
    "home.for_you": "మీ కోసం",
    "home.categories": "వర్గాలు",
    "home.end_of_products": "ఉత్పత్తుల ముగింపు",
    "home.search_placeholder": "ఉత్పత్తుల కోసం వెతకండి…",

    // Categories page
    "categories.title": "వర్గాలు",
    "categories.subtitle": "వర్గం ద్వారా ఉత్పత్తులను బ్రౌజ్ చేయండి",
    "categories.chocolates": "చాక్లెట్‌లు",
    "categories.ladoos": "లడ్డూలు",
    "categories.biscuits": "బిస్కెట్‌లు",
    "categories.cakes": "కేక్‌లు",
    "categories.hot_snacks": "వేడి స్నాక్‌లు",
    "categories.chocolates_desc": "మధుర చాక్లెట్ ట్రీట్‌లు",
    "categories.ladoos_desc": "సంప్రదాయ భారతీయ మిఠాయిలు",
    "categories.biscuits_desc": "క్రిస్పీ మరియు రుచికరమైన బిస్కెట్‌లు",
    "categories.cakes_desc": "రుచికరమైన మరియు తాజా కేక్‌లు",
    "categories.hot_snacks_desc": "అల్పాహారం మరియు క్రిస్పీ స్నాక్‌లు",

    // Bottom navigation
    "nav.home": "హోమ్",
    "nav.categories": "వర్గాలు",
    "nav.account": "ఖాతా",
    "nav.cart": "కార్ట్",

    // Sorting
    "sort.title": "వరుస క్రమం",
    "sort.price_low_high": "ధర: తక్కువ నుండి ఎక్కువ",
    "sort.price_high_low": "ధర: ఎక్కువ నుండి తక్కువ",
    "sort.popularity": "జనాదరణ",
    "sort.newest": "కొత్త వస్తువులు",
    "sort.best_selling": "అత్యధిక అమ్మకాలు",

    // Home page extended
    "home.topSelling": "🔥 అత్యధిక అమ్మకాలు",
    "home.topSellingSubtitle": "ఈ వారం అత్యంత ప్రజాదరణ పొందిన ఉత్పత్తులు",
    "home.downloadApp": "మెరుగైన అనుభవం కోసం, ఇప్పుడే Vyapara Setu డౌన్‌లోడ్ చేయండి",
    "home.downloadAppSub": "మా మొబైల్ యాప్‌తో అత్యుత్తమ షాపింగ్ అనుభవం పొందండి",
    "home.downloadBtn": "యాప్ డౌన్‌లోడ్ చేయండి",
    "home.learnMore": "మరింత తెలుసుకోండి",
    "home.deliverTo": "డెలివరీ చేయడానికి",
    "home.searchPlaceholder": "ఉత్పత్తులు, బ్రాండ్లు మరియు మరిన్నింటి కోసం వెతకండి",

    // Product
    "product.addToCart": "కార్ట్‌కి జోడించండి",
    "product.outOfStock": "స్టాక్ లేదు",
    "product.inStock": "స్టాక్‌లో ఉంది",
    "product.topBadge": "టాప్",
    "product.viewDetails": "వివరాలు చూడండి",
    "product.mrp": "గరిష్ట చిల్లర ధర",
    "product.off": "తగ్గింపు",
    "product.weight": "బరువు",

    // Cart page
    "cart.title": "నా కార్ట్",
    "cart.empty": "మీ కార్ట్ ఖాళీగా ఉంది",
    "cart.emptySubtitle": "ప్రారంభించడానికి వస్తువులు జోడించండి",
    "cart.subtotal": "ఉప మొత్తం",
    "cart.deliveryFee": "డెలివరీ రుసుము",
    "cart.total": "మొత్తం",
    "cart.checkout": "చెక్అవుట్‌కు వెళ్ళండి",
    "cart.free": "ఉచితం",
    "cart.remove": "తొలగించు",
    "cart.continueShopping": "షాపింగ్ కొనసాగించండి",
    "cart.items": "వస్తువులు",

    // Checkout page
    "checkout.title": "చెక్అవుట్",
    "checkout.secureCheckout": "సురక్షిత చెక్అవుట్",
    "checkout.deliveryAddress": "డెలివరీ చిరునామా",
    "checkout.changeAddress": "చిరునామా మార్చండి",
    "checkout.paymentMethod": "చెల్లింపు పద్ధతి",
    "checkout.editPayment": "చెల్లింపు పద్ధతి సవరించండి",
    "checkout.upi": "UPI (సిఫార్సు చేయబడింది)",
    "checkout.upiDesc": "Google Pay, PhonePe, Paytm తో చెల్లించండి",
    "checkout.upiId": "UPI ID",
    "checkout.upiHint": "మీ UPI ID నమోదు చేయండి. మీ ఫోన్‌కు చెల్లింపు అభ్యర్థన పంపబడుతుంది.",
    "checkout.card": "క్రెడిట్ / డెబిట్ కార్డ్",
    "checkout.cardDesc": "Visa, Mastercard, RuPay",
    "checkout.netbanking": "నెట్ బ్యాంకింగ్",
    "checkout.netbankingDesc": "మీ బ్యాంక్ నుండి నేరుగా చెల్లించండి",
    "checkout.cod": "డెలివరీపై నగదు",
    "checkout.codDesc": "ఆర్డర్ వచ్చినప్పుడు చెల్లించండి",
    "checkout.reviewItems": "వస్తువులు మరియు షిప్పింగ్ సమీక్షించండి",
    "checkout.delivery": "డెలివరీ",
    "checkout.orderTotal": "ఆర్డర్ మొత్తం",
    "checkout.securePayment": "Razorpay ద్వారా సురక్షిత చెల్లింపు",
    "checkout.processing": "ప్రాసెస్ అవుతోంది…",
    "checkout.pay": "చెల్లించండి",
    "checkout.addAddressForDelivery": "డెలివరీ రుసుము లెక్కించడానికి డెలివరీ చిరునామా జోడించండి",
    "checkout.orderSummary": "ఆర్డర్ సారాంశం",
    "checkout.placeOrder": "ఆర్డర్ చేయండి",
    "checkout.online": "ఆన్‌లైన్ చెల్లింపు",
    "checkout.addAddress": "కొత్త చిరునామా జోడించండి",
    "checkout.selectAddress": "చిరునామా ఎంచుకోండి",
    "checkout.noAddress": "చిరునామా ఎంచుకోబడలేదు",

    // Orders page
    "orders.title": "నా ఆర్డర్లు",
    "orders.empty": "ఇంకా ఆర్డర్లు లేవు",
    "orders.emptySubtitle": "మీ ఆర్డర్లను ఇక్కడ చూడటానికి షాపింగ్ ప్రారంభించండి",
    "orders.pending": "పెండింగ్‌లో ఉంది",
    "orders.confirmed": "నిర్ధారించబడింది",
    "orders.processing": "ప్రాసెసింగ్‌లో ఉంది",
    "orders.shipped": "షిప్ అయింది",
    "orders.delivered": "డెలివరీ అయింది",
    "orders.cancelled": "రద్దు చేయబడింది",
    "orders.trackOrder": "ఆర్డర్ ట్రాక్ చేయండి",
    "orders.reorder": "మళ్ళీ ఆర్డర్ చేయండి",
    "orders.viewDetails": "వివరాలు చూడండి",
    "orders.placedOn": "ఆర్డర్ చేసిన తేదీ",
    "orders.total": "మొత్తం",

    // Product Detail page
    "productDetail.description": "వివరణ",
    "productDetail.reviews": "సమీక్షలు",
    "productDetail.relatedProducts": "సంబంధిత ఉత్పత్తులు",
    "productDetail.quantity": "పరిమాణం",
    "productDetail.buyNow": "ఇప్పుడే కొనండి",
    "productDetail.specifications": "వివరణలు",
    "productDetail.brand": "బ్రాండ్",
    "productDetail.category": "వర్గం",

    // Auth
    "auth.login": "లాగిన్",
    "auth.signup": "సైన్ అప్",
    "auth.email": "ఇమెయిల్",
    "auth.password": "పాస్‌వర్డ్",
    "auth.forgotPassword": "పాస్‌వర్డ్ మర్చిపోయారా?",
    "auth.noAccount": "ఖాతా లేదా?",
    "auth.hasAccount": "ఇప్పటికే ఖాతా ఉందా?",
    "auth.orContinueWith": "లేదా దీనితో కొనసాగించండి",
    "auth.googleLogin": "Google తో కొనసాగించండి",
    "auth.name": "పూర్తి పేరు",
    "auth.phone": "ఫోన్ నంబర్",
    "auth.createAccount": "ఖాతా సృష్టించండి",
    "auth.loginTitle": "మీ ఖాతాకు లాగిన్ చేయండి",
    "auth.signupTitle": "మీ ఖాతాను సృష్టించండి",
    "auth.rememberMe": "నన్ను గుర్తుంచుకో",
    "auth.logout": "లాగ్ అవుట్",
    "auth.orContinueWithOTP": "లేదా OTP తో కొనసాగించండి",
    "auth.emailOrPhone": "ఇమెయిల్ లేదా ఫోన్ నంబర్",
    "auth.emailOrPhonePlaceholder": "మీ ఇమెయిల్ లేదా ఫోన్ నంబర్ నమోదు చేయండి",
    "auth.otp": "OTP",
    "auth.otpPlaceholder": "6-అంకెల OTP నమోదు చేయండి",
    "auth.verifyingOTP": "OTP ధృవీకరిస్తోంది...",
    "auth.sendingOTP": "OTP పంపుతోంది...",
    "auth.verifyOTP": "OTP ధృవీకరించు",
    "auth.sendOTP": "OTP పంపు",
    "auth.useDifferentContact": "వేరే ఇమెయిల్ లేదా ఫోన్ నంబర్ ఉపయోగించండి",
    "auth.mobileNumber": "మొబైల్ నంబర్",
    "auth.mobilePlaceholder": "మీ 10-అంకెల మొబైల్ నంబర్ నమోదు చేయండి",
    "auth.verified": "ధృవీకరించబడింది",
    "auth.sending": "పంపుతోంది...",
    "auth.verify": "ధృవీకరించు",
    "auth.submitting": "సమర్పిస్తోంది...",
    "auth.submit": "సమర్పించు",
    "auth.resendOTP": "OTP మళ్ళీ పంపు",
    "auth.resendIn": "మళ్ళీ పంపడానికి",
    "auth.mobileVerified": "మొబైల్ నంబర్ విజయవంతంగా ధృవీకరించబడింది",
    "auth.namePlaceholder": "మీ పేరు నమోదు చేయండి",
    "auth.emailPlaceholder": "మీ ఇమెయిల్ నమోదు చేయండి",
    "auth.passwordPlaceholder": "మీ పాస్‌వర్డ్ నమోదు చేయండి",
    "auth.confirmPassword": "పాస్‌వర్డ్ నిర్ధారించు",
    "auth.confirmPasswordPlaceholder": "మీ పాస్‌వర్డ్ నిర్ధారించండి",
    "auth.creatingAccount": "ఖాతా సృష్టిస్తోంది...",

    // Settings page
    "settings.title": "సెట్టింగులు",
    "settings.subtitle": "మీ ఖాతా ప్రాధాన్యతలను నిర్వహించండి",
    "settings.managePreferences": "మీ ఖాతా ప్రాధాన్యతలను నిర్వహించండి",
    "settings.notifications": "నోటిఫికేషన్ ప్రాధాన్యతలు",
    "settings.loadingPrefs": "ప్రాధాన్యతలు లోడవుతున్నాయి…",
    "settings.orderUpdates": "ఆర్డర్ అప్‌డేట్లు",
    "settings.orderUpdatesDesc": "మీ ఆర్డర్ స్థితి గురించి తెలియజేయండి",
    "settings.promotions": "ప్రమోషన్లు",
    "settings.promotionsDesc": "ప్రత్యేక ఆఫర్లు & డీల్స్",
    "settings.newsletter": "న్యూస్‌లెటర్",
    "settings.newsletterDesc": "వారపు అప్‌డేట్లు",
    "settings.sms": "SMS నోటిఫికేషన్లు",
    "settings.smsDesc": "SMS ద్వారా డెలివరీ అప్‌డేట్లు",
    "settings.appearance": "స్వరూపం",
    "settings.language": "భాష",
    "settings.languageDesc": "మీకు నచ్చిన భాషను ఎంచుకోండి",
    "settings.currency": "కరెన్సీ",
    "settings.currencyDesc": "మీ కరెన్సీలో ధరలు చూపించు",
    "settings.privacy": "గోప్యత & భద్రత",
    "settings.privacySecurity": "గోప్యత & భద్రత",
    "settings.changePassword": "పాస్‌వర్డ్ మార్చండి",
    "settings.currentPassword": "ప్రస్తుత పాస్‌వర్డ్",
    "settings.logout": "లాగ్అవుట్",
    "settings.deleteAccount": "ఖాతాను తొలగించండి",
    "settings.deleteWarning": "ఈ చర్యను రద్దు చేయడం సాధ్యం కాదు",
    "settings.downloadData": "నా డేటా డౌన్‌లోడ్ చేయండి",
    "settings.dangerZone": "ప్రమాద జోన్",
    "settings.dangerZoneDesc": "మీ ఖాతా మరియు అన్ని సంబంధిత డేటాను శాశ్వతంగా తొలగించండి.",
    "settings.deleting": "తొలగిస్తోంది...",
    "settings.needHelp": "సహాయం కావాలా? మా",
    "settings.helpCenter": "సహాయం కేంద్రం",
    "settings.changing": "మార్చుతోంది...",
    "settings.loginToAccess": "మీ సెట్టింగ్‌లను యాక్సెస్ చేయడానికి దయచేసి లాగిన్ అవ్వండి.",
    "settings.goToLogin": "లాగిన్‌కు వెళ్ళండి",

    // Common extended
    "common.loading": "లోడవుతోంది...",
    "common.error": "ఏదో తప్పు జరిగింది",
    "common.retry": "మళ్ళీ ప్రయత్నించండి",
    "common.save": "సేవ్ చేయి",
    "common.cancel": "రద్దు చేయి",
    "common.confirm": "నిర్ధారించు",
    "common.back": "వెనుకకు",
    "common.next": "తదుపరి",
    "common.done": "పూర్తయింది",
    "common.filter": "ఫిల్టర్",
    "common.sort": "క్రమబద్ధీకరణ",
    "common.apply": "వర్తింపజేయి",
    "common.clear": "క్లియర్",
    "common.noResults": "ఫలితాలు కనుగొనబడలేదు",
    "common.seeAll": "అన్నీ చూడండి",
    "common.rupee": "₹",
    "common.success": "విజయం",
    "common.warning": "హెచ్చరిక",
    "common.info": "సమాచారం",
    "common.required": "అవసరం",
  },
  hi: {
    // Account page
    "account.title": "खाता",
    "account.welcome": "अपनी खाता सेटिंग्स प्रबंधित करें",
    "account.welcome.authenticated": "स्वागत है, {{name}}!",
    "account.profile": "प्रोफ़ाइल",
    "account.profile.description": "अपनी व्यक्तिगत जानकारी प्रबंधित करें",
    "account.orders": "ऑर्डर",
    "account.orders.description": "अपना ऑर्डर इतिहास देखें",
    "account.settings": "सेटिंग्स",
    "account.settings.description": "ऐप प्राथमिकताएं और कॉन्फ़िगरेशन",
    "account.notifications": "सूचनाएं",
    "account.notifications.description":
      "अपनी सूचना प्राथमिकताएं प्रबंधित करें",
    "account.privacy": "गोपनीयता",
    "account.privacy.description": "अपनी गोपनीयता सेटिंग्स नियंत्रित करें",
    "account.help": "सहायता और समर्थन",
    "account.help.description": "सहायता प्राप्त करें और समर्थन से संपर्क करें",
    "account.logout": "लॉग आउट",
    "account.logout.description": "अपने खाते से साइन आउट करें",
    "account.language": "भाषा",
    "account.language.description": "अपनी पसंदीदा भाषा चुनें",
    "account.language.english": "English",
    "account.language.telugu": "తెలుగు",
    "account.language.hindi": "हिन्दी",

    // Profile form
    "profile.edit": "प्रोफ़ाइल संपादित करें",
    "profile.name": "नाम",
    "profile.email": "ईमेल",
    "profile.phone": "फोन",
    "profile.address": "पता",
    "profile.save": "परिवर्तन सहेजें",
    "profile.cancel": "रद्द करें",

    // Common
    "common.shop_now": "अभी खरीदें",
    "common.add_to_cart": "कार्ट में जोड़ें",
    "common.search": "खोजें",
    "common.cart": "कार्ट",
    "common.home": "होम",
    "common.categories": "श्रेणियां",
    "common.account": "खाता",

    // Home page
    "home.for_you": "आपके लिए",
    "home.categories": "श्रेणियां",
    "home.end_of_products": "उत्पादों का अंत",
    "home.search_placeholder": "उत्पादों के लिए खोजें…",

    // Categories page
    "categories.title": "श्रेणियां",
    "categories.subtitle": "श्रेणी के अनुसार उत्पाद ब्राउज़ करें",
    "categories.chocolates": "चॉकलेट",
    "categories.ladoos": "लड्डू",
    "categories.biscuits": "बिस्कुट",
    "categories.cakes": "केक",
    "categories.hot_snacks": "हॉट स्नैक्स",
    "categories.chocolates_desc": "मीठे चॉकलेट ट्रीट्स",
    "categories.ladoos_desc": "पारंपरिक भारतीय मिठाई",
    "categories.biscuits_desc": "कुरकुरे और स्वादिष्ट बिस्कुट",
    "categories.cakes_desc": "स्वादिष्ट और ताजे केक",
    "categories.hot_snacks_desc": "मसालेदार और कुरकुरे स्नैक्स",

    // Bottom navigation
    "nav.home": "होम",
    "nav.categories": "श्रेणियां",
    "nav.account": "खाता",
    "nav.cart": "कार्ट",

    // Sorting
    "sort.title": "क्रमबद्ध करें",
    "sort.price_low_high": "मूल्य: कम से ज्यादा",
    "sort.price_high_low": "मूल्य: ज्यादा से कम",
    "sort.popularity": "लोकप्रियता",
    "sort.newest": "नवीनतम आगमन",
    "sort.best_selling": "सबसे ज्यादा बिकने वाले",

    // Home page extended
    "home.topSelling": "🔥 सर्वाधिक बिकने वाले",
    "home.topSellingSubtitle": "इस सप्ताह सबसे लोकप्रिय उत्पाद",
    "home.downloadApp": "बेहतर अनुभव के लिए, अभी Vyapara Setu डाउनलोड करें",
    "home.downloadAppSub": "हमारे मोबाइल ऐप से सर्वोत्तम शॉपिंग अनुभव प्राप्त करें",
    "home.downloadBtn": "ऐप डाउनलोड करें",
    "home.learnMore": "और जानें",
    "home.deliverTo": "डिलीवरी करें",
    "home.searchPlaceholder": "उत्पाद, ब्रांड और अधिक खोजें",

    // Product
    "product.addToCart": "कार्ट में जोड़ें",
    "product.outOfStock": "स्टॉक में नहीं",
    "product.inStock": "स्टॉक में है",
    "product.topBadge": "शीर्ष",
    "product.viewDetails": "विवरण देखें",
    "product.mrp": "अधिकतम खुदरा मूल्य",
    "product.off": "छूट",
    "product.weight": "वजन",

    // Cart page
    "cart.title": "मेरी कार्ट",
    "cart.empty": "आपकी कार्ट खाली है",
    "cart.emptySubtitle": "शुरू करने के लिए आइटम जोड़ें",
    "cart.subtotal": "उप-योग",
    "cart.deliveryFee": "डिलीवरी शुल्क",
    "cart.total": "कुल",
    "cart.checkout": "चेकआउट करें",
    "cart.free": "मुफ़्त",
    "cart.remove": "हटाएं",
    "cart.continueShopping": "खरीदारी जारी रखें",
    "cart.items": "आइटम",

    // Checkout page
    "checkout.title": "चेकआउट",
    "checkout.secureCheckout": "सुरक्षित चेकआउट",
    "checkout.deliveryAddress": "डिलीवरी पता",
    "checkout.changeAddress": "पता बदलें",
    "checkout.paymentMethod": "भुगतान विधि",
    "checkout.editPayment": "भुगतान विधि संपादित करें",
    "checkout.upi": "UPI (अनुशंसित)",
    "checkout.upiDesc": "Google Pay, PhonePe, Paytm से भुगतान करें",
    "checkout.upiId": "UPI ID",
    "checkout.upiHint": "अपना UPI ID दर्ज करें। आपके फोन पर भुगतान अनुरोध भेजा जाएगा।",
    "checkout.card": "क्रेडिट / डेबिट कार्ड",
    "checkout.cardDesc": "Visa, Mastercard, RuPay",
    "checkout.netbanking": "नेट बैंकिंग",
    "checkout.netbankingDesc": "अपने बैंक से सीधे भुगतान करें",
    "checkout.cod": "डिलीवरी पर नकद",
    "checkout.codDesc": "ऑर्डर आने पर भुगतान करें",
    "checkout.reviewItems": "आइटम और शिपिंग समीक्षा करें",
    "checkout.delivery": "डिलीवरी",
    "checkout.orderTotal": "ऑर्डर कुल",
    "checkout.securePayment": "Razorpay द्वारा सुरक्षित भुगतान",
    "checkout.processing": "प्रसंस्करण…",
    "checkout.pay": "भुगतान करें",
    "checkout.addAddressForDelivery": "डिलीवरी शुल्क की गणना के लिए डिलीवरी पता जोड़ें",
    "checkout.orderSummary": "ऑर्डर सारांश",
    "checkout.placeOrder": "ऑर्डर दें",
    "checkout.online": "ऑनलाइन भुगतान",
    "checkout.addAddress": "नया पता जोड़ें",
    "checkout.selectAddress": "पता चुनें",
    "checkout.noAddress": "कोई पता चयनित नहीं",

    // Orders page
    "orders.title": "मेरे ऑर्डर",
    "orders.empty": "अभी तक कोई ऑर्डर नहीं",
    "orders.emptySubtitle": "अपने ऑर्डर यहाँ देखने के लिए खरीदारी शुरू करें",
    "orders.pending": "लंबित",
    "orders.confirmed": "पुष्टि हुई",
    "orders.processing": "प्रसंस्करण",
    "orders.shipped": "भेज दिया गया",
    "orders.delivered": "डिलीवर हुआ",
    "orders.cancelled": "रद्द किया",
    "orders.trackOrder": "ऑर्डर ट्रैक करें",
    "orders.reorder": "फिर से ऑर्डर करें",
    "orders.viewDetails": "विवरण देखें",
    "orders.placedOn": "ऑर्डर की तारीख",
    "orders.total": "कुल",

    // Product Detail page
    "productDetail.description": "विवरण",
    "productDetail.reviews": "समीक्षाएं",
    "productDetail.relatedProducts": "संबंधित उत्पाद",
    "productDetail.quantity": "मात्रा",
    "productDetail.buyNow": "अभी खरीदें",
    "productDetail.specifications": "विशिष्टताएं",
    "productDetail.brand": "ब्रांड",
    "productDetail.category": "श्रेणी",

    // Auth
    "auth.login": "लॉगिन",
    "auth.signup": "साइन अप",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.forgotPassword": "पासवर्ड भूल गए?",
    "auth.noAccount": "खाता नहीं है?",
    "auth.hasAccount": "पहले से खाता है?",
    "auth.orContinueWith": "या इसके साथ जारी रखें",
    "auth.googleLogin": "Google से जारी रखें",
    "auth.name": "पूरा नाम",
    "auth.phone": "फ़ोन नंबर",
    "auth.createAccount": "खाता बनाएं",
    "auth.loginTitle": "अपने खाते में लॉगिन करें",
    "auth.signupTitle": "अपना खाता बनाएं",
    "auth.rememberMe": "मुझे याद रखें",
    "auth.logout": "लॉगआउट",
    "auth.orContinueWithOTP": "या OTP के साथ जारी रखें",
    "auth.emailOrPhone": "ईमेल या फ़ोन नंबर",
    "auth.emailOrPhonePlaceholder": "अपना ईमेल या फ़ोन नंबर दर्ज करें",
    "auth.otp": "OTP",
    "auth.otpPlaceholder": "6-अंकीय OTP दर्ज करें",
    "auth.verifyingOTP": "OTP सत्यापित हो रहा है...",
    "auth.sendingOTP": "OTP भेजा जा रहा है...",
    "auth.verifyOTP": "OTP सत्यापित करें",
    "auth.sendOTP": "OTP भेजें",
    "auth.useDifferentContact": "दूसरा ईमेल या फ़ोन नंबर उपयोग करें",
    "auth.mobileNumber": "मोबाइल नंबर",
    "auth.mobilePlaceholder": "अपना 10-अंकीय मोबाइल नंबर दर्ज करें",
    "auth.verified": "सत्यापित",
    "auth.sending": "भेजा जा रहा है...",
    "auth.verify": "सत्यापित करें",
    "auth.submitting": "जमा किया जा रहा है...",
    "auth.submit": "जमा करें",
    "auth.resendOTP": "OTP पुनः भेजें",
    "auth.resendIn": "पुनः भेजें",
    "auth.mobileVerified": "मोबाइल नंबर सफलतापूर्वक सत्यापित",
    "auth.namePlaceholder": "अपना नाम दर्ज करें",
    "auth.emailPlaceholder": "अपना ईमेल दर्ज करें",
    "auth.passwordPlaceholder": "अपना पासवर्ड दर्ज करें",
    "auth.confirmPassword": "पासवर्ड की पुष्टि करें",
    "auth.confirmPasswordPlaceholder": "अपना पासवर्ड कन्फर्म करें",
    "auth.creatingAccount": "खाता बनाया जा रहा है...",

    // Settings page
    "settings.title": "सेटिंग्स",
    "settings.subtitle": "अपनी खाता प्राथमिकताएं प्रबंधित करें",
    "settings.managePreferences": "अपनी खाता प्राथमिकताएं प्रबंधित करें",
    "settings.notifications": "सूचना प्राथमिकताएं",
    "settings.loadingPrefs": "प्राथमिकताएं लोड हो रही हैं…",
    "settings.orderUpdates": "ऑर्डर अपडेट",
    "settings.orderUpdatesDesc": "अपनी ऑर्डर स्थिति के बारे में सूचित रहें",
    "settings.promotions": "प्रमोशन",
    "settings.promotionsDesc": "विशेष ऑफर और डील्स",
    "settings.newsletter": "न्यूज़लेटर",
    "settings.newsletterDesc": "साप्ताहिक अपडेट",
    "settings.sms": "SMS सूचनाएं",
    "settings.smsDesc": "SMS के माध्यम से डिलीवरी अपडेट",
    "settings.appearance": "उपस्थिति",
    "settings.language": "भाषा",
    "settings.languageDesc": "अपनी पसंदीदा भाषा चुनें",
    "settings.currency": "मुद्रा",
    "settings.currencyDesc": "अपनी मुद्रा में कीमतें दिखाएं",
    "settings.privacy": "गोपनीयता और सुरक्षा",
    "settings.privacySecurity": "गोपनीयता और सुरक्षा",
    "settings.changePassword": "पासवर्ड बदलें",
    "settings.currentPassword": "वर्तमान पासवर्ड",
    "settings.logout": "लॉगआउट",
    "settings.deleteAccount": "खाता हटाएं",
    "settings.deleteWarning": "यह क्रिया पूर्ववत नहीं की जा सकती",
    "settings.downloadData": "मेरा डेटा डाउनलोड करें",
    "settings.dangerZone": "खतरा क्षेत्र",
    "settings.dangerZoneDesc": "अपना खाता और सभी संबंधित डेटा स्थायी रूप से हटाएं।",
    "settings.deleting": "हटाया जा रहा है...",
    "settings.needHelp": "मदद चाहिए? हमारा",
    "settings.helpCenter": "सहायता केंद्र",
    "settings.changing": "बदला जा रहा है...",
    "settings.loginToAccess": "अपनी सेटिंग्स एक्सेस करने के लिए कृपया लॉगिन करें।",
    "settings.goToLogin": "लॉगिन पर जाएं",

    // Common extended
    "common.loading": "लोड हो रहा है...",
    "common.error": "कुछ गलत हो गया",
    "common.retry": "फिर से प्रयास करें",
    "common.save": "सहेजें",
    "common.cancel": "रद्द करें",
    "common.confirm": "पुष्टि करें",
    "common.back": "वापस",
    "common.next": "अगला",
    "common.done": "हो गया",
    "common.filter": "फ़िल्टर",
    "common.sort": "क्रमबद्ध",
    "common.apply": "लागू करें",
    "common.clear": "साफ करें",
    "common.noResults": "कोई परिणाम नहीं मिला",
    "common.seeAll": "सभी देखें",
    "common.rupee": "₹",
    "common.success": "सफल",
    "common.warning": "चेतावनी",
    "common.info": "जानकारी",
    "common.required": "आवश्यक",
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "en";
  });

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem("app-language", newLanguage);
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let translation =
      translations[language][
        key as keyof (typeof translations)[typeof language]
      ] || key;

    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        translation = translation.replace(`{{${paramKey}}}`, value);
      });
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
